name: riverpod_recursos_nativos
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.4.1
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  permission_handler: ^11.0.1
  random_name_generator: ^1.2.0
  sensors_plus: ^3.1.0
  share_plus: ^7.2.1
  uuid: ^4.1.0
  local_auth: ^2.1.7

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  

flutter:

  uses-material-design: true
  assets:
    - assets/compass/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
